### ISSUE TITLE
could not preform the payment as it is redirecting him to the cart page

### ISSUE THREAD

**Issue by aessamm** [alibasheer/woo-mpgs#2]
it is a great plugin but it has some issue

i created an order ob behalf of one of my clients from the back-end & sent him the link to make the payment but he could not preform the payment as it is redirecting him to the cart page & showing the message

“Checkout is not available whilst your cart is empty.”

**Comment by alibasheer** [comment]
Hi @aessamm,

Yeah I saw it, I will work on that and let you know once fixed in the next couple of days.

Thank you for your feedback.

**Comment by joyloli** [comment]
Ho Ali, hope you having a good day, have you fixed the empty cart issue!? 
Is there a way to help me using the bank integration files directly?!
Regards

**Comment by alibasheer** [comment]
Hi @aessamm, Hi @joyloli , please note that I fixed this issue in the plugin a while ago.
Closing this ticket
